-- CreateEnum
CREATE TYPE "PRODUCT_CONDITION" AS ENUM ('NEW', 'USED_LIKE_NEW', 'USED_IN_GOOD_SHAPE', 'USED');

-- CreateEnum
CREATE TYPE "PRODUCT_STATE" AS ENUM ('TO_SELL', 'TO_BUY', 'TO_LOAN', 'TO_REQUEST_LOANING', 'TO_TRADE');

-- CreateEnum
CREATE TYPE "PRODUCT_CATEGORIES" AS ENUM ('CAR', 'APARTMENT', 'HOUSEHOLDS_AND_FAMILY', 'SPORTS', 'ELECTRONICS', 'HEALTH', 'BUSINESS', 'JOBS');

-- CreateEnum
CREATE TYPE "PRODUCT_CURRENCY" AS ENUM ('ALL', 'EUR', 'USD', 'GBP', 'OTHER');

-- CreateEnum
CREATE TYPE "PRODUCT_ADVERT_INDEX" AS ENUM ('GOLD', 'SILVER', 'REGULAR');

-- CreateEnum
CREATE TYPE "PRODUCT_PREFERRED_COMMUNICATION" AS ENUM ('TEL', 'WHATSAPP', 'EMAIL');

-- CreateEnum
CREATE TYPE "PRODUCT_SUBCATEGORIES" AS ENUM ('CAR__CARS', 'CAR__CAR_PARTS', 'CAR__MOTORBIKE', 'CAR__SCOOTER', 'CAR__BIKE_SCOOTER_PARTS', 'CAR__CAMPING_AUTO', 'CAR__FARMING_AUTO', 'CAR__TOTALED_AUTO_PARTS', 'CAR__HEAVY_DUTY_MACHINES', 'CAR__BOATS_AND_NAVY', 'APARTMENT__HOUSE', 'APARTMENT__APARTMENT', 'APARTMENT__VILLA', 'APARTMENT__AREA', 'APARTMENT__KIOSKS', 'HOUSEHOLDS__HOUSE_DECOR', 'HOUSEHOLDS__INDOOR_MACHINES', 'HOUSEHOLDS__CHILDREN', 'HOUSEHOLDS__HOUSE_PARTS', 'HOUSEHOLDS__HOUSE_FURNITURES', 'HOUSEHOLDS__HOUSE_KITCHEN', 'HOUSEHOLDS__HOUSE_BATHROOM', 'SPORTS__GYM_EQUIPMENT', 'SPORTS__OUTDOOR_EQUIPMENT', 'ELECTRONICS__SMARTPHONES', 'ELECTRONICS__LAPTOPS', 'ELECTRONICS__PC', 'ELECTRONICS__ACCESSORIES', 'ELECTRONICS__SMART_PARTS', 'ELECTRONICS__IOT', 'ELECTRONICS__TVS', 'ELECTRONICS__TABLETS', 'ELECTRONICS__CONSOLES', 'ELECTRONICS__AUDIO', 'HEALTH__GYM_SUPPLEMENTS', 'HEALTH__HEALTH_CONTENT', 'HEALTH__HEALTH_MACHINES', 'BUSINESS__BUSINESS_AREAS', 'BUSINESS__BUSINESS_FURNITURE', 'BUSINESS__BUSINESS_SERVICES', 'JOBS__FULL_TIME', 'JOBS__PART_TIME');

-- CreateTable
CREATE TABLE "Product" (
    "id" TEXT NOT NULL,
    "category" "PRODUCT_CATEGORIES" NOT NULL,
    "currency" "PRODUCT_CURRENCY" NOT NULL,
    "advertIndex" "PRODUCT_ADVERT_INDEX" NOT NULL,
    "preferredCommunication" "PRODUCT_PREFERRED_COMMUNICATION" NOT NULL,
    "subcategory" "PRODUCT_SUBCATEGORIES" NOT NULL,
    "condition" "PRODUCT_CONDITION" NOT NULL,

    CONSTRAINT "Product_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "User" (
    "id" TEXT NOT NULL,
    "fullName" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "draftProductId" TEXT,

    CONSTRAINT "User_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Draft_Product_Form" (
    "draftId" TEXT NOT NULL,
    "title" TEXT NOT NULL,
    "debatablePrice" BOOLEAN NOT NULL,
    "description" TEXT NOT NULL,
    "images" TEXT[],
    "location" TEXT NOT NULL,
    "price" INTEGER NOT NULL,
    "advertIndex" "PRODUCT_ADVERT_INDEX" NOT NULL,
    "category" "PRODUCT_CATEGORIES" NOT NULL,
    "subCategory" "PRODUCT_SUBCATEGORIES" NOT NULL,
    "telephone" TEXT NOT NULL,
    "whatsapp" TEXT,
    "email" TEXT NOT NULL,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "slug" TEXT NOT NULL,
    "fullName" TEXT NOT NULL,
    "currency" "PRODUCT_CURRENCY" NOT NULL,
    "details" JSONB NOT NULL,
    "state" "PRODUCT_STATE" NOT NULL,
    "condition" "PRODUCT_CONDITION" NOT NULL,
    "userId" TEXT,
    "preferredCommunication" "PRODUCT_PREFERRED_COMMUNICATION" NOT NULL,
    "deliveryAtYourPlace" BOOLEAN NOT NULL,

    CONSTRAINT "Draft_Product_Form_pkey" PRIMARY KEY ("draftId")
);

-- CreateIndex
CREATE UNIQUE INDEX "Product_id_key" ON "Product"("id");

-- CreateIndex
CREATE UNIQUE INDEX "User_id_key" ON "User"("id");

-- AddForeignKey
ALTER TABLE "Draft_Product_Form" ADD CONSTRAINT "Draft_Product_Form_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;
